name: Run tests and upload coverage

on:
  push:
    branches:
      - mywork       # runs when you push to your personal branch
      - develop      # runs when pushing to develop
  pull_request:
    branches:
      - develop      # runs on PRs into develop
      - main         # runs on PRs into main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # adjust if you need a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage
        run: pytest --cov=SeqKit_tools --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
